package com.neusoft.model;

import java.sql.Timestamp;

/**
 * approvals
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Approvals implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -935576953662918325L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** applicantId */
    private Integer applicantId;

    /** approverId */
    private Integer approverId;

    /** businessType */
    private String businessType;

    /** businessId */
    private Integer businessId;

    /** status */
    private String status;

    /** createdAt */
    private Timestamp createdAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取applicantId
     * 
     * @return applicantId
     */
    public Integer getApplicantId() {
        return this.applicantId;
    }

    /**
     * 设置applicantId
     * 
     * @param applicantId
     */
    public void setApplicantId(Integer applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * 获取approverId
     * 
     * @return approverId
     */
    public Integer getApproverId() {
        return this.approverId;
    }

    /**
     * 设置approverId
     * 
     * @param approverId
     */
    public void setApproverId(Integer approverId) {
        this.approverId = approverId;
    }

    /**
     * 获取businessType
     * 
     * @return businessType
     */
    public String getBusinessType() {
        return this.businessType;
    }

    /**
     * 设置businessType
     * 
     * @param businessType
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * 获取businessId
     * 
     * @return businessId
     */
    public Integer getBusinessId() {
        return this.businessId;
    }

    /**
     * 设置businessId
     * 
     * @param businessId
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}