package com.neusoft.model;

import java.sql.Time;
import java.util.Date;

/**
 * attendance_records
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class AttendanceRecords implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3074215750935431327L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** workDate */
    private Date workDate;

    /** shiftId */
    private Integer shiftId;

    /** checkIn */
    private Time checkIn;

    /** checkOut */
    private Time checkOut;

    /** status */
    private String status;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取workDate
     * 
     * @return workDate
     */
    public Date getWorkDate() {
        return this.workDate;
    }

    /**
     * 设置workDate
     * 
     * @param workDate
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * 获取shiftId
     * 
     * @return shiftId
     */
    public Integer getShiftId() {
        return this.shiftId;
    }

    /**
     * 设置shiftId
     * 
     * @param shiftId
     */
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * 获取checkIn
     * 
     * @return checkIn
     */
    public Time getCheckIn() {
        return this.checkIn;
    }

    /**
     * 设置checkIn
     * 
     * @param checkIn
     */
    public void setCheckIn(Time checkIn) {
        this.checkIn = checkIn;
    }

    /**
     * 获取checkOut
     * 
     * @return checkOut
     */
    public Time getCheckOut() {
        return this.checkOut;
    }

    /**
     * 设置checkOut
     * 
     * @param checkOut
     */
    public void setCheckOut(Time checkOut) {
        this.checkOut = checkOut;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}