package com.neusoft.model;

import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

/**
 * attendance_retroactive
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class AttendanceRetroactive implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 125930044114461842L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** workDate */
    private LocalDate workDate;

    /** retroIn */
    private LocalTime retroIn;

    /** retroOut */
    private LocalTime retroOut;

    /** approverId */
    private Integer approverId;

    /** status */
    private String status;

    /** createdAt */
    private Timestamp createdAt;

    /** reason */
    private String reason;

    /** attendanceId */
    private Integer attendanceId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取workDate
     * 
     * @return workDate
     */
    public LocalDate getWorkDate() {
        return this.workDate;
    }

    /**
     * 设置workDate
     * 
     * @param workDate
     */
    public void setWorkDate(LocalDate workDate) {
        this.workDate = workDate;
    }

    /**
     * 获取retroIn
     * 
     * @return retroIn
     */
    public LocalTime getRetroIn() {
        return this.retroIn;
    }

    /**
     * 设置retroIn
     * 
     * @param retroIn
     */
    public void setRetroIn(LocalTime retroIn) {
        this.retroIn = retroIn;
    }

    /**
     * 获取retroOut
     * 
     * @return retroOut
     */
    public LocalTime getRetroOut() {
        return this.retroOut;
    }

    /**
     * 设置retroOut
     * 
     * @param retroOut
     */
    public void setRetroOut(LocalTime retroOut) {
        this.retroOut = retroOut;
    }

    /**
     * 获取approverId
     * 
     * @return approverId
     */
    public Integer getApproverId() {
        return this.approverId;
    }

    /**
     * 设置approverId
     * 
     * @param approverId
     */
    public void setApproverId(Integer approverId) {
        this.approverId = approverId;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 获取reason
     * 
     * @return reason
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * 设置reason
     * 
     * @param reason
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 获取attendanceId
     * 
     * @return attendanceId
     */
    public Integer getAttendanceId() {
        return this.attendanceId;
    }

    /**
     * 设置attendanceId
     * 
     * @param attendanceId
     */
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}