package com.neusoft.model;

import com.baomidou.mybatisplus.annotation.TableField;

import java.sql.Timestamp;

/**
 * departments
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Departments implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 7781016195829081098L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** deptName */
    private String deptName;

    /** leaderId */
    private Integer leaderId;

    /** createdAt */
    private Timestamp createdAt;
    private String status;
    @TableField("father_dept")
    private Integer fatherDept;
    private Integer deptQuota;

    public Integer getFatherDept() {
        return fatherDept;
    }

    public void setFatherDept(Integer fatherDept) {
        this.fatherDept = fatherDept;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    public Integer getDeptQuota() {
        return deptQuota;
    }

    public void setDeptQuota(Integer deptQuota) {
        this.deptQuota = deptQuota;
    }
    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取deptName
     * 
     * @return deptName
     */
    public String getDeptName() {
        return this.deptName;
    }

    /**
     * 设置deptName
     * 
     * @param deptName
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * 获取leaderId
     * 
     * @return leaderId
     */
    public Integer getLeaderId() {
        return this.leaderId;
    }

    /**
     * 设置leaderId
     * 
     * @param leaderId
     */
    public void setLeaderId(Integer leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}