package com.neusoft.model;

import io.swagger.models.auth.In;

/**
 * employee_vacation_balance
 * 
 * @author bianj
 * @version 1.0.0 2025-09-24
 */
public class EmployeeVacationBalance implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 840835905133584452L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** typeId */
    private Integer typeId;

    /** year */
    private Integer year;

    /** totalDays */
    private Integer totalDays;

    /** usedDays */
    private Integer usedDays;

    /** remainingDays */
    private Integer remainingDays;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取typeId
     * 
     * @return typeId
     */
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * 设置typeId
     * 
     * @param typeId
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 获取year
     * 
     * @return year
     */
    public Integer getYear() {
        return this.year;
    }

    /**
     * 设置year
     * 
     * @param year
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * 获取totalDays
     * 
     * @return totalDays
     */
    public Integer getTotalDays() {
        return this.totalDays;
    }

    /**
     * 设置totalDays
     * 
     * @param totalDays
     */
    public void setTotalDays(Integer totalDays) {
        this.totalDays = totalDays;
    }

    /**
     * 获取usedDays
     * 
     * @return usedDays
     */
    public Integer getUsedDays() {
        return this.usedDays;
    }

    /**
     * 设置usedDays
     * 
     * @param usedDays
     */
    public void setUsedDays(Integer usedDays) {
        this.usedDays = usedDays;
    }

    /**
     * 获取remainingDays
     * 
     * @return remainingDays
     */
    public Integer getRemainingDays() {
        return this.remainingDays;
    }

    /**
     * 设置remainingDays
     * 
     * @param remainingDays
     */
    public void setRemainingDays(Integer remainingDays) {
        this.remainingDays = remainingDays;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}