package com.neusoft.model;

import java.sql.Timestamp;

/**
 * employee_history
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class EmployeeHistory implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 844999269881999757L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** changeType */
    private String changeType;

    /** oldValue */
    private String oldValue;

    /** newValue */
    private String newValue;

    /** changeDate */
    private Timestamp changeDate;

    public Timestamp getEndTime() {
        return endTime;
    }

    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    private Timestamp endTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取changeType
     * 
     * @return changeType
     */
    public String getChangeType() {
        return this.changeType;
    }

    /**
     * 设置changeType
     * 
     * @param changeType
     */
    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }

    /**
     * 获取oldValue
     * 
     * @return oldValue
     */
    public String getOldValue() {
        return this.oldValue;
    }

    /**
     * 设置oldValue
     * 
     * @param oldValue
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    /**
     * 获取newValue
     * 
     * @return newValue
     */
    public String getNewValue() {
        return this.newValue;
    }

    /**
     * 设置newValue
     * 
     * @param newValue
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    /**
     * 获取changeDate
     * 
     * @return changeDate
     */
    public Timestamp getChangeDate() {
        return this.changeDate;
    }

    /**
     * 设置changeDate
     * 
     * @param changeDate
     */
    public void setChangeDate(Timestamp changeDate) {
        this.changeDate = changeDate;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}