package com.neusoft.model;

import java.sql.Timestamp;
import java.util.Date;

/**
 * employee_shifts
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class EmployeeShifts implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -9074582741199285650L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** shiftId */
    private Integer shiftId;

    /** effectiveDate */
    private Date effectiveDate;

    /** assignedAt */
    private Timestamp assignedAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取shiftId
     * 
     * @return shiftId
     */
    public Integer getShiftId() {
        return this.shiftId;
    }

    /**
     * 设置shiftId
     * 
     * @param shiftId
     */
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    /**
     * 获取effectiveDate
     * 
     * @return effectiveDate
     */
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    /**
     * 设置effectiveDate
     * 
     * @param effectiveDate
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * 获取assignedAt
     * 
     * @return assignedAt
     */
    public Timestamp getAssignedAt() {
        return this.assignedAt;
    }

    /**
     * 设置assignedAt
     * 
     * @param assignedAt
     */
    public void setAssignedAt(Timestamp assignedAt) {
        this.assignedAt = assignedAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}