package com.neusoft.model;

import java.sql.Timestamp;
import java.util.Date;

/**
 * employees
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Employees implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -275511894502611369L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** gender */
    private String gender;

    /** birthday */
    private Date birthday;

    /** phone */
    private String phone;

    /** hireDate */
    private Date hireDate;

    /** deptId */
    private Integer deptId;

    /** jobId */
    private Integer jobId;

    /** maritalStatus */
    private String maritalStatus;

    /** status */
    private String status;
    private String salary;

    public String getSalary() {
        return salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    /** createdAt */
    private Timestamp createdAt;

    public Timestamp getFirstWorkDate() {
        return firstWorkDate;
    }

    public void setFirstWorkDate(Timestamp firstWorkDate) {
        this.firstWorkDate = firstWorkDate;
    }

    private Timestamp firstWorkDate;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取gender
     * 
     * @return gender
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * 设置gender
     * 
     * @param gender
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * 获取birthday
     * 
     * @return birthday
     */
    public Date getBirthday() {
        return this.birthday;
    }

    /**
     * 设置birthday
     * 
     * @param birthday
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 获取phone
     * 
     * @return phone
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * 设置phone
     * 
     * @param phone
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取hireDate
     * 
     * @return hireDate
     */
    public Date getHireDate() {
        return this.hireDate;
    }

    /**
     * 设置hireDate
     * 
     * @param hireDate
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * 获取deptId
     * 
     * @return deptId
     */
    public Integer getDeptId() {
        return this.deptId;
    }

    /**
     * 设置deptId
     * 
     * @param deptId
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * 获取jobId
     * 
     * @return jobId
     */
    public Integer getJobId() {
        return this.jobId;
    }

    /**
     * 设置jobId
     * 
     * @param jobId
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * 获取maritalStatus
     * 
     * @return maritalStatus
     */
    public String getMaritalStatus() {
        return this.maritalStatus;
    }

    /**
     * 设置maritalStatus
     * 
     * @param maritalStatus
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}