package com.neusoft.model;

import java.sql.Timestamp;

/**
 * jobs
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Jobs implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8282285656523317673L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** jobName */
    private String jobName;

    /** createdAt */
    private Timestamp createdAt;
    private Integer jobLevel;
    private String status;

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getJobLevel() {
        return jobLevel;
    }

    public void setJobLevel(Integer jobLevel) {
        this.jobLevel = jobLevel;
    }

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public int getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取jobName
     * 
     * @return jobName
     */
    public String getJobName() {
        return this.jobName;
    }

    /**
     * 设置jobName
     * 
     * @param jobName
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}