package com.neusoft.model;

import java.sql.Timestamp;

/**
 * operation_logs
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class OperationLogs implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3454836697919583318L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** userId */
    private Integer userId;

    /** action */
    private String action;

    /** targetTable */
    private String targetTable;

    /** targetId */
    private Integer targetId;

    /** createdAt */
    private Timestamp createdAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取action
     * 
     * @return action
     */
    public String getAction() {
        return this.action;
    }

    /**
     * 设置action
     * 
     * @param action
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * 获取targetTable
     * 
     * @return targetTable
     */
    public String getTargetTable() {
        return this.targetTable;
    }

    /**
     * 设置targetTable
     * 
     * @param targetTable
     */
    public void setTargetTable(String targetTable) {
        this.targetTable = targetTable;
    }

    /**
     * 获取targetId
     * 
     * @return targetId
     */
    public Integer getTargetId() {
        return this.targetId;
    }

    /**
     * 设置targetId
     * 
     * @param targetId
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}