package com.neusoft.model;

/**
 * permissions
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Permissions implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4600534867442347684L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** permissionName */
    private String permissionName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取permissionName
     * 
     * @return permissionName
     */
    public String getPermissionName() {
        return this.permissionName;
    }

    /**
     * 设置permissionName
     * 
     * @param permissionName
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}