package com.neusoft.model;

/**
 * role_permissions
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class RolePermissions implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 715142294425693975L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** roleId */
    private Integer roleId;

    /** permissionId */
    private Integer permissionId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取roleId
     * 
     * @return roleId
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * 设置roleId
     * 
     * @param roleId
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取permissionId
     * 
     * @return permissionId
     */
    public Integer getPermissionId() {
        return this.permissionId;
    }

    /**
     * 设置permissionId
     * 
     * @param permissionId
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}