package com.neusoft.model;

/**
 * roles
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Roles implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2606599341609176972L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** roleName */
    private String roleName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取roleName
     * 
     * @return roleName
     */
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * 设置roleName
     * 
     * @param roleName
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}