package com.neusoft.model;

/**
 * user_roles
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class UserRoles implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2868443001737135650L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** userId */
    private Integer userId;

    /** roleId */
    private Integer roleId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取roleId
     * 
     * @return roleId
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * 设置roleId
     * 
     * @param roleId
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}