package com.neusoft.model;

import java.sql.Timestamp;

/**
 * users
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class Users implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 592003327723741944L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** username */
    private String username;

    /** email */
    private String email;

    /** password */
    private String password;

    /** status */
    private String status;

    /** employeeId */
    private Integer employeeId;

    /** createdAt */
    private Timestamp createdAt;

    /** updatedAt */
    private Timestamp updatedAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取username
     * 
     * @return username
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * 设置username
     * 
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * 获取email
     * 
     * @return email
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * 设置email
     * 
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取password
     * 
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置password
     * 
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 获取updatedAt
     * 
     * @return updatedAt
     */
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * 设置updatedAt
     * 
     * @param updatedAt
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}