package com.neusoft.model;

/**
 * vacation_types
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class VacationTypes implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3618434900608567380L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** typeName */
    private String typeName;

    /** limited */
    private Boolean limited;

    /** refreshPolicy */
    private String refreshPolicy;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取typeName
     * 
     * @return typeName
     */
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * 设置typeName
     * 
     * @param typeName
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * 获取limited
     * 
     * @return limited
     */
    public Boolean getLimited() {
        return this.limited;
    }

    /**
     * 设置limited
     * 
     * @param limited
     */
    public void setLimited(Boolean limited) {
        this.limited = limited;
    }

    /**
     * 获取refreshPolicy
     * 
     * @return refreshPolicy
     */
    public String getRefreshPolicy() {
        return this.refreshPolicy;
    }

    /**
     * 设置refreshPolicy
     * 
     * @param refreshPolicy
     */
    public void setRefreshPolicy(String refreshPolicy) {
        this.refreshPolicy = refreshPolicy;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}