package com.neusoft.model;

import java.sql.Timestamp;
import java.sql.Date;
import java.time.LocalDate;

/**
 * vacation_requests
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class VacationRequests implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8669746813044897395L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** employeeId */
    private Integer employeeId;

    /** typeId */
    private Integer typeId;

    /** startDate */
    private LocalDate startDate;

    /** endDate */
    private LocalDate endDate;

    /** totalDays */
    private Integer totalDays;

    /** approverId */
    private Integer approverId;

    /** status */
    private String status;

    /** createdAt */
    private Timestamp createdAt;

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    private String reason;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取employeeId
     * 
     * @return employeeId
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * 设置employeeId
     * 
     * @param employeeId
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * 获取typeId
     * 
     * @return typeId
     */
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * 设置typeId
     * 
     * @param typeId
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * 获取startDate
     * 
     * @return startDate
     */
    public LocalDate getStartDate() {
        return this.startDate;
    }

    /**
     * 设置startDate
     * 
     * @param startDate
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * 获取endDate
     * 
     * @return endDate
     */
    public LocalDate getEndDate() {
        return this.endDate;
    }

    /**
     * 设置endDate
     * 
     * @param endDate
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * 获取totalDays
     * 
     * @return totalDays
     */
    public Integer getTotalDays() {
        return this.totalDays;
    }

    /**
     * 设置totalDays
     * 
     * @param totalDays
     */
    public void setTotalDays(Integer totalDays) {
        this.totalDays = totalDays;
    }

    /**
     * 获取approverId
     * 
     * @return approverId
     */
    public Integer getApproverId() {
        return this.approverId;
    }

    /**
     * 设置approverId
     * 
     * @param approverId
     */
    public void setApproverId(Integer approverId) {
        this.approverId = approverId;
    }

    /**
     * 获取status
     * 
     * @return status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 设置status
     * 
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}