package com.neusoft.model;

import java.sql.Time;

/**
 * work_shifts
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class WorkShifts implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7988597691806110420L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** shiftName */
    private String shiftName;

    /** startTime */
    private Time startTime;

    /** endTime */
    private Time endTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取shiftName
     * 
     * @return shiftName
     */
    public String getShiftName() {
        return this.shiftName;
    }

    /**
     * 设置shiftName
     * 
     * @param shiftName
     */
    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    /**
     * 获取startTime
     * 
     * @return startTime
     */
    public Time getStartTime() {
        return this.startTime;
    }

    /**
     * 设置startTime
     * 
     * @param startTime
     */
    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    /**
     * 获取endTime
     * 
     * @return endTime
     */
    public Time getEndTime() {
        return this.endTime;
    }

    /**
     * 设置endTime
     * 
     * @param endTime
     */
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}