package com.neusoft.model;

import java.sql.Date;

/**
 * work_calendar
 * 
 * @author bianj
 * @version 1.0.0 2025-09-22
 */
public class WorkCalendar implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 6658164745133656008L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** workDate */
    private Date workDate;

    /** dayType */
    private String dayType;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取workDate
     * 
     * @return workDate
     */
    public Date getWorkDate() {
        return this.workDate;
    }

    /**
     * 设置workDate
     * 
     * @param workDate
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * 获取dayType
     * 
     * @return dayType
     */
    public String getDayType() {
        return this.dayType;
    }

    /**
     * 设置dayType
     * 
     * @param dayType
     */
    public void setDayType(String dayType) {
        this.dayType = dayType;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}